### ISSUE TITLE
Стертые подсветки текста остаются в программе

### ISSUE THREAD

**Issue by Geniusssmit** [sallyruthstruik/PocketbookAnnotations#1]
После того как подсветка удалена, при экспорте в .md, да и вообще в программе остаются стертые заметки

**Comment by sallyruthstruik** [comment]
Hello, I'm using in-memory cache for storing data. Do you see removed annotations after program (guis/run.py) restart? If yes, it means that removed annotations are in cache and I can fix it very easily

**Comment by Geniusssmit** [comment]
No, nothing changes, that's the problem. If I unintentionally highlight something, it's forever in annotations. That's annoying..

**Comment by Geniusssmit** [comment]
I mean.. after I remove annotation, it still there for some reason

**Comment by sallyruthstruik** [comment]
Interesting, when you're deleting the anno, it isn't really removed from the sqlite database, so it seems that there is a "removed" flag which I haven't taken into account. 

I'll try to find and implement it
