### ISSUE TITLE
Now it's not working at all

### ISSUE THREAD

**Issue by Geniusssmit** [sallyruthstruik/PocketbookAnnotations#4]
After that last fix
![4AW7R6P0nE](https://user-images.githubusercontent.com/24941285/58267743-e311d180-7d8c-11e9-81e1-334e6e88f4d1.jpg)

**Comment by sallyruthstruik** [comment]
Oh, I have a bug in my .gitignore so some important files were missed. Gonna fix today

**Comment by sallyruthstruik** [comment]
In future it is possible to add travis-ci build which will check such silly bugs

**Comment by sallyruthstruik** [comment]
Fixed, please give a try

**Comment by Geniusssmit** [comment]
Now it's working! And deleted highlights working as expected. Thanks !

**Comment by Geniusssmit** [comment]
I'm not sure that version in release branch is updated btw

**Comment by sallyruthstruik** [comment]
> I'm not sure that version in release branch is updated btw

Checked, it should be in master. I haven't created a standalone release for the fix. On this week I'll try to implement CI build.

Closing this issue, if you'll have other problems - please open the new one.
